

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: realm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-system:
    build: ./realm-authentication-system
    ports:
      - "8081:8081"
    env_file:
      - ./realm-authentication-system/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  realm-backend:
    build:
      context: .
      dockerfile: ./realm-backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./realm-backend/.env
    depends_on:
      - postgres
      - redis
      - auth-system

  realm-frontend:
    build: ./realm-frontend
    ports:
      - "3000:80"
    env_file:
      - ./realm-frontend/.env
    depends_on:
      - realm-backend

volumes:
  postgres_data: