// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Password            string         `json:"password"`
	EmailVerified       sql.NullBool   `json:"email_verified"`
	EmailVerifyToken    sql.NullString `json:"email_verify_token"`
	PasswordResetToken  sql.NullString `json:"password_reset_token"`
	PasswordResetExpiry sql.NullTime   `json:"password_reset_expiry"`
	FailedLoginAttempts sql.NullInt32  `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime   `json:"locked_until"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}
