// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPasswordResetToken(ctx context.Context, passwordResetToken sql.NullString) (User, error)
	IncrementFailedLoginAttempts(ctx context.Context, arg IncrementFailedLoginAttemptsParams) error
	ResetFailedLoginAttempts(ctx context.Context, arg ResetFailedLoginAttemptsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	VerifyEmail(ctx context.Context, arg VerifyEmailParams) error
}

var _ Querier = (*Queries)(nil)
